### ISSUE TITLE
Add support for ROCCAT Kone Aimo Remastered

### ISSUE THREAD

**Issue by X3n0m0rph59** [X3n0m0rph59/eruption#50]
This issue will track the progress on the support for the ROCCAT Kone Aimo Remastered

_Originally posted by @greenseeker in https://github.com/X3n0m0rph59/eruption/issues/47#issuecomment-787514702_

**Comment by X3n0m0rph59** [comment]
@greenseeker, thanks for providing the capture file! Since I currently do not have access to a ROCCAT Kone Aimo Remastered, this is entirely untested.

**Comment by Shinigami92** [comment]
If I can help in any way, feel free to contact me
I bought a Roccat Kone Aimo Remastered just now and it will (hopefully) arrive tomorrow :slightly_smiling_face: 

My system:
```yml
Operating System: Arch Linux
KDE Plasma Version: 5.22.2
KDE Frameworks Version: 5.83.0
Qt Version: 5.15.2
Kernel Version: 5.10.47-1-lts (64-bit)
Graphics Platform: X11
Processors: 28 × Intel® Core™ i9-10940X CPU @ 3.30GHz
Memory: 62.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1080/PCIe/SSE2
```
